"""empty message

Revision ID: 5329ae7b2303
Revises: 
Create Date: 2018-12-25 16:04:20.587095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5329ae7b2303'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'card', ['hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='unique')
    op.drop_column('card', 'hash')
    # ### end Alembic commands ###
